// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvjxxxbwetuheuotnudj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52anh4eGJ3ZXR1aGV1b3RudWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzYzMjEsImV4cCI6MjA2ODQxMjMyMX0.uclVpg9UO4DlKwQmJdH7ILJWI1LDa4VA2MFyYjFZ85w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});